language: haskell

cache: apt
before_install:
    - sudo add-apt-repository ppa:glondu/ppa -y
    - sudo apt-get update
    - sudo apt-get install coq-8.4
script:
    - make
    - cd Haskell
    - make test
